### ISSUE TITLE
[ASLabelNode] Create a simpler alternative to ASTextNode

### ISSUE THREAD

**Issue by secretiverhyme** [facebookarchive/AsyncDisplayKit#152]
ASTextNode's `attributedString` API is overkill for a simple, uniformly-styled label.  Consider—

``` objective-c
ASLabelNode *label = [[ASLabelNode alloc] init];
label.textColor = [UIColor grayColor];
label.font = [UIFont systemFontOfSize:12.0f];
label.text = @"hello";
```

—versus—

``` objective-c
ASTextNode *label = [[ASTextNode alloc] init];
NSDictionary *attributes = @{ NSForegroundColorAttributeName: [UIColor grayColor],
                                         NSFontAttributeName: [UIFont systemFontOfSize:12.0f] };
NSAttributedString *attributedString = [[NSAttributedString alloc] initWithString:@"hello"
                                                                       attributes:attributes];
```

**Comment by ocrickard** [comment]
I'd be OK with this so long as we don't add it to ASTextNode and do not subclass.  In order to add it to ASTextNode we'd have to add a new prerender stage to wrap the attributed string with the default attributes, something I'm **very** against for performance reasons.

The actual implementation of ASLabelNode could just wrap an ASTextNode or perhaps a further extracted ASTextNodeRenderer/friends.  It could lazily generate an attributed string and pass it into the same backend as ASTextNode.

For the record I believe subclassing of concrete leaf nodes like ASTextNode should be seen as an antipattern.  Composition makes refactors I'm working on much easier.

**Comment by secretiverhyme** [comment]
+1 @ocrickard.  An ASLabelNode that's a stripped-down counterpart to ASTextNode would be a useful addition to the framework, but using ASTextNodeRenderer directly rather than subclassing or expanding ASTextNode is the way to go.

**Comment by ide** [comment]
UILabel's adjustsFontSizeToFitWidth and numberOfLines properties are also sometimes really helpful and seem like it'd be good to offload them to a background thread. I'd actually like ASTextNode to support these (and ASLabelNode, too, by delegating to a text node) since the inconsistent APIs across UILabel/UITextField/UITextView are a pain point of UIKit.

**Comment by ocrickard** [comment]
It's trivial to add maximumNumberOfLines property on ASTextNode as-is.  The ASTextNodeRenderer would just have to set it on the NSTextContainer.  We're open to Pull-requests!

**Comment by ocrickard** [comment]
Re adjustsFontSizeToFitWidth: the performance of a recursive sizing algorithm is very poor.  Although I agree with you that it's well-suited to async layout, I'd hesitate adding it directly to ASTextNode because it would substantially complicate the internal architecture and if used heavily would substantially degrade performance of applications who used it.  The NSAttributedString for ASTextNode is the first and only source of truth on font sizing.

If we wanted this for ASLabelNode though I think that would be a better fit.  Basically if you don't mind a slow, inexact text node for quick and dirty implementations, go for ASLabelNode, if you want to control everything yourself and have intense performance requirements, you want ASTextNode's single-directional data pipeline.

**Comment by nolanw** [comment]
I'd totally use ASLabelNode if it existed, to avoid creating nearly identical two-element attribute dictionaries for every single ASTextNode I make.

That alone probably isn't a good enough reason to do ASLabelNode.

**Comment by appleguy** [comment]
Let's make sure to adopt the improved text rendering engine from CK (which is an evolution of the ASDK renderer) before doing this.

**Comment by appleguy** [comment]
@secretiverhyme @cfcommando @zdenektopic @ocrickard @ide @nolanw - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#98
