### ISSUE TITLE
[ASTableNode, ASCollectionNode] willBeginBatchFetchWithContext called right after viewDidAppear

### ISSUE THREAD

**Issue by jsspalding** [facebookarchive/AsyncDisplayKit#1631]
ASDK version: 1.9.73 (May 4)

With both ASTableView and ASCollectionView, willBeginBatchFetchWithContext is being called right after viewDidAppear even without any input/touch.

Please, correct me if I'm wrong but this is not the same behaviour as version 1.9.7 and I think that batchFetch is not supposed to be called without a scroll event toward the end of the scrollview.

@appleguy could you please take a look at this? We are ready to release an app with 1.9.73, should I downgrade to 1.9.7 or wait for a fix? Thanks!

**Comment by appleguy** [comment]
This is actually intentional, provided that the end of the contentSize is within the number of screens for batch fetching.  The previous implementation did not handle a few important cases such as if the initially loaded content didn't have enough space to scroll, it would never load at all.

If you'd like the previous behavior, feel free to set the number to 0 and then make it the desired number of screens ahead for loading once you see the first scrollViewDidBeginScrolling:

If you notice a bug, such as the load being started even when you have a contentSize (determined by items in the data source) big enough to fill the number of screen dimensions below / to the right of the initial, definitely let us know those details and we will aim to fix in the upcoming 1.9.8 release.

Michael, is it possible that for some apps, the first layout batch size might not cover enough size and we trigger a load before allowing the layout batches to finish?  I assume this is fully handled already as I believe your code is using the completion event of all layout from the initial load finishing.

**Comment by hannahmbanana** [comment]
cc @maicki

**Comment by jsspalding** [comment]
Thanks for replying so quickly! It's now clear for me how the new implementation is better.

I did some tests here and I think there is an issue but I can't say if it's in my code or ASDK.

I had an array `stories` with 70 items, nodeForRowAtIndexPath is correctly called returning an ASCellNode for each item, at this point there was no cells rendered and batchFetch was called.

```
(lldb) po stories.count
70

(lldb) po tableView.contentSize
▿ CGSize
  - width : 375.0
  - height : 0.0
```

After the execution of batchFetch, with the cells rendered:

```
(lldb) po tableView.contentSize
▿ CGSize
  - width : 375.0
  - height : 23171.0
```

I think this is something related to what you're asking Michael. Please let me know if I can help with anything else!

**Comment by hannahmbanana** [comment]
@jsspalding: FYI, `nodeBlockForRowAtIndexPath:` is now the preferred method over `nodeForRowAtIndexPath` for concurrent initialization / display of an ASTableNode's cells. There is an equivalent method -  `nodeBlockForItemAtIndexPath:` - for ASCollectionNodes as well. Just make sure the returned ASCellNodeBlock is thread safe!

http://asyncdisplaykit.org/docs/containers-astablenode.html 
http://asyncdisplaykit.org/docs/containers-astablenode.html#node-block-thread-safety-warning

**Comment by jsspalding** [comment]
@hannahmbanana thanks! I didn't check the documentation for some time, it's greatly improved!
I have one question: shouldn't we return cellNode instead of ASCellNode() here?

```
// this may be executed on a background thread - it is important to make sure it is thread safe

    let cellNodeBlock = { () -> ASCellNode in
        let cellNode = PhotoCellNode(photo: photoModel)
        cellNode.delegate = self;
        return ASCellNode()
    }

```

**Comment by hannahmbanana** [comment]
@jsspalding: The documentation is a work-in-progress still, but much improved from before. 

You should also join our Slack Channel (see #1582). We answer questions even more quickly over there. :) 

I am not familiar with Swift, but yes, that does make sense. Perhaps you can translate / interpret from the Objective-C block for now? There should be a switch at the top of the code blocks on the website. 

@lappp9 - can you check if our documentation is incorrect here?

**Comment by jsspalding** [comment]
@hannahmbanana sure, I'm not an obj-c developer but I can understand it :)
I can confirm this one for you, I'm 100% sure that we should return the cellNode we just created with `let cellNode`.
I have just implemented `nodeBlockForRowAtIndexPath` to replace `nodeForRowAtIndexPath` and the behaviour is exactly the same as https://github.com/facebook/AsyncDisplayKit/issues/1631#issuecomment-217585646.
I will check the Slack channel soon! Thanks!

**Comment by maicki** [comment]
@jsspalding @hannahmbanana Yes it should return cellNode in that block for the documentation

**Comment by hannahmbanana** [comment]
@jsspalding: I wasn't expecting this to fix the batchFetching issue, just wanted to let you know that `nodeForRowAtIndexPath:` is no longer the most performant method. :)

**Comment by maicki** [comment]
@jsspalding @appleguy This behavior is intentional as @appleguy already explained, otherwise batch fetch would never be called after the first layout if the first page content size is smaller as the bounds of the ASCollectionView or the ASTableView.

Furthermore to the question of @appleguy we wait until the first batch or reload finished until we actually try to check if we should do a batch fetch as we call them in delegate methods after sections / nodes or animations are finished.

**Comment by jsspalding** [comment]
@maicki thanks for the info. Still, I'm failing to understand why batchFetch is being called before the tableNode.view.contentSize has any chance to be greater than zero.

Please, you can confirm this behaviour with the ASDK Swift example.
The only change needed is at `ViewController.swift` line 20, increase the itemCount so the height of the contents would be way higher than the default 2 screens ahead for loading.

From:
`static let empty = State(itemCount: 20, fetchingMore: false)`
To:
`static let empty = State(itemCount: 400, fetchingMore: false)`

As I see what @appleguy said, in this case batchFetch should _not_ be triggered.
This is generating an undesired/unnecessary network call asking for more content in my app.
I think the issue here is that batchFetch is being called before contentSize has any chance to be greater than zero.

Please guys, I will really appreciate if you can confirm this behaviour.

If it's correct the way it is, I will implement the @appleguy suggestion of set the number of screens ahead to 0 and then change it once I see the first scrollViewDidBeginScrolling, although it looks like a workaround to me.

**Comment by hannahmbanana** [comment]
@maicki: sorry to bug you again, but are you able to answer this question? This does sound odd.

**Comment by maicki** [comment]
@jsspalding I can confirm that the actual implementation is not optimal and I'm currently working on improving batch fetching that should fix this issue. At the moment I think you should go with @appleguy suggestion

cc @hannahmbanana @appleguy

**Comment by jsspalding** [comment]
@maicki thank you!

**Comment by maicki** [comment]
To get a bit more information on this issue: We first need a reliable way from within `ASDataController` to be able to know when certain batch updates finished completely (so inserts / deletes / updates where performed) to be able to inform the delegate that it's time to perform a batch fetch.

@Adlai-Holler Any update on an API like that ("data controller did finish" or something similar) or should we file a new issue specifically for that?

**Comment by garrettmoon** [comment]
Marking as P3 as it sounds like there's a workaround.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#134
