### ISSUE TITLE
[ASTableView] nodeForRowAtIndexPath/nodeBlockForRowAtIndexPath is called for all nodes in VERY big table view

### ISSUE THREAD

**Issue by mikhailmulyar** [facebookarchive/AsyncDisplayKit#2226]
At the moment i see that ASTableView requests all nodes from the list of about 500 items, so nodeForRowAtIndexPath/nodeBlockForRowAtIndexPath is called for all those items right at the start.
Is this expected behaviour?

**Comment by hannahmbanana** [comment]
@mikhailmulyar: Yes, this is expected behavior as we trigger asynchronous and concurrent  measuring of `ASCellNodes` when they are first created (rather than right before they come onscreen as UIKit does). A few notes: 
- The lightweight node is created upfront, but as long as you don't touch it's view or layer in `init` (see more about this in [Subclassing Nodes](http://asyncdisplaykit.org/docs/subclassing.html)), then those expensive components won't be created until they are likely to be needed as a part of ASDK's [Intelligent Preloading](http://asyncdisplaykit.org/docs/intelligent-preloading.html) system.
- We recommend that you start with a smaller initial set of nodes, maybe 300, and use the [Batch Fetching API](http://asyncdisplaykit.org/docs/batch-fetching-api.html) to load more as the user scrolls. See this in action with the [ASDKgram example](https://github.com/facebook/AsyncDisplayKit/tree/master/examples/ASDKgram)

**Comment by mikhailmulyar** [comment]
Ok, thanks. I see now how it works. Is batch fetching works in both direction of scrolling? I can't find the way how to understand from which side i should fetch data.

**Comment by hannahmbanana** [comment]
@mikhailmulyar: Currently, the Batch Fetching API only works in the downward direction. If you want to go in the opposite direction (e.g. a message application) there's a transform trick I've seen alluded to in other comments. Let me know if this is what you want and I'll see if I can find it.

**Comment by mikhailmulyar** [comment]
Yes, i'm currently looking how to implement it. Not only for messaging, but for really long lists also. In my opinion it is good to have ability to scroll and batch fetch in both directions and release data which scrolled really far away. And when user scrolls back refetch it again. That's why i was a bit surprised that all ASCellNodes requested from the start. I thought there is some range of nodes which stays in memory (bigger than screen), but not whole list. And was expecting that it is dynamically released and refetched when needed

**Comment by mikhailmulyar** [comment]
@hannahmbanana: I've found solution you are talking about in #1750. However i'm not sure it what i'm looking for. Generally what i want to achieve is:
There is very long list of items, 10000, for example. User can search through this items and enter list in the place of any item. So if he founds item at row - 5000, and enters table in that point, i want to load 100 items, 50 before and 50 after this item. After that user can scroll in both directions and i want to batch fetch items from top or bottom depending of scroll direction.
Mostly in a way how intelligent preloading described in docs (interface state "fetch data" works in both directions). But it seems it is how AsyncDisplayKit works under the hood and batch fetching api is another thing.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#144
