### ISSUE TITLE
NavigationController is nil inside ASCellNode

### ISSUE THREAD

**Issue by MarvinNazari** [facebookarchive/AsyncDisplayKit#2616]
When using `ASCellNode(viewControllerBlock:` the viewController dosent inherit the `navigationController` so it returns nil, this is when i use `ASPagerNode`

using `1.9.90`

**Comment by hannahmbanana** [comment]
@MarvinNazari - This is also possible to implement, but has been something we've needed ourselves yet.

**Comment by MarvinNazari** [comment]
@hannahmbanana Im not really sure how can i implement this, i think the problem is that when adding a view controller inside a another view controller we need to use `addChildViewController` and `didMoveToParentViewController` but thats not possible inside a `ASCellNode`
Any idea?

**Comment by Adlai-Holler** [comment]
@MarvinNazari What we need in order pull this off, is:

- In `willDisplayCell:`, get the view controller that owns the `ASCollectionView` (you can do this by repeatedly calling `-nextResponder` until a view controller is returned) and call `addChildViewController` and `didMoveToParentViewController:` with the cell node's view controller.
- In `didEndDisplayingCell:`, call `willMoveToParentViewController:nil` and then `removeFromParentViewController` on the cell node's view controller.

Since `ASTableView` and `ASCollectionView` will both have to do this, you may want to create methods like `-[ASCellNode associateWithViewControllerForView:(UIView *)]` `-[ASCellNode disassociateFromViewController` to hold the duplicated code.

**Comment by Andy1984** [comment]
Same problem. You need to `addChildViewController` in `- (ASCellNode *)pagerNode:(ASPagerNode *)pagerNode nodeAtIndex:(NSInteger)index`

**Comment by garrettmoon** [comment]
Going to close this as it seems like it was addressed. If not, please feel free to open a new issue in the Texture repo: https://github.com/texturegroup/texture/issues
