### ISSUE TITLE
ASNetworkImageNode can NOT load animatedData sometime

### ISSUE THREAD

**Issue by IvanChan** [facebookarchive/AsyncDisplayKit#2871]
[ASDK 2.0.1]

I realized **ASImageDownloaderProtocol** & **ASImageCacheProtocol**  for `ASNetworkImageNode`

static image works well

load gif data  sometimes just got a blank imageNode for display

the api below is called normally
```
- (nullable id <ASAnimatedImageProtocol>)animatedImageWithData:(NSData *)animatedImageData
{
    return (id <ASAnimatedImageProtocol>)[[PINAnimatedImage alloc] initWithAnimatedImageData:animatedImageData];
}

```

**Comment by hannahmbanana** [comment]
@IvanChan - are you implementing a custom image downloader? I don't think we have tested this feature with anything except PINRemoteImage (what we use at Pinterest). Is there any reason you aren't able to use PINRemoteImage? 

Without a example project that includes the downloader you are using, realistically we won't be able to prioritize this issue since 95% of our users are on PINRemoteImage. I suggest you use FLAnimatedImage as a workaround.

**Comment by IvanChan** [comment]
YES, I have a lot of stat for image download, so I implementing a custom image downloader with SDWebImage.

But I set breakpoint for downloader callback, the data is indeed gif-data, and passed to `animatedImageWithData `, I currently work around with some other logic to play gif instead of passing data to `ASNetworkImageNode`.

I can post a sample project later , sorry for recently busy.

By the way, It's not friendly for user to **manager cache** for `ASNetworkImageNode` with default downloader?

**Comment by garrettmoon** [comment]
@IvanChan GIFs are currently broken in ASDK master sadly, it's fixed in PINRemoteImage master though. Can you check to see if that fixes the issue for you?

**Comment by ay8s** [comment]
@garrettmoon Looks like it's fixed with the latest master PINRemoteImage for us. 👍

**Comment by garrettmoon** [comment]
Going to close this out, yay!
