### ISSUE TITLE
Huge gifs inside repo

### ISSUE THREAD

**Issue by MarvinNazari** [facebookarchive/AsyncDisplayKit#3029]
Everyone likes GIF and i don't wanna be a party pooper, but the `Screenshots` folder inside example folder is `64,6 MB`. I tried to compress them with ImageOptim and we get `45,1 MB` afterwards. but is it really that important to have them inside the repo?
#2968 
cc @hannahmbanana

**Comment by maicki** [comment]
Agree with @MarvinNazari 

@hannahmbanana Can we move them out of the repo to some other image hosting place or into our documentation repo and link to it from there?

**Comment by hannahmbanana** [comment]
Good call. :)

**Comment by appleguy** [comment]
@MarvinNazari thanks for filing this.  I noticed it when they went in, but since they were already committed, figured it wasn't worth dealing with.

Does anyone know how to actually scrub the files from history?  I don't think deleting them from the repo will be enough to remove them from the clone, as Git has to be able to regenerate them if an older commit is checked out.

**Comment by MarvinNazari** [comment]
@appleguy maybe [this](https://help.github.com/articles/removing-sensitive-data-from-a-repository/#using-the-bfg) can help? I haven't try it personally.

**Comment by maicki** [comment]
@hannahmbanana Would you be able to tackle that this week:

- Move the gifs to a different place
- Link to new place
- Remove from history

Thanks!

**Comment by hannahmbanana** [comment]
I'm nervous about wiping the repo's history.

https://rtyley.github.io/bfg-repo-cleaner/

**Comment by appleguy** [comment]
The best way to wipe the history appears to be:

- Remove the files in the normal way. They will still be downloaded in a git clone, however.
- Let all PRs cycle so that new / active work branches have a commit where the files are removed. Thanks to great efforts by the core team, this is practical because the PR list is kept pretty small these days!
- Finally, once the coast is clear, do https://rtyley.github.io/bfg-repo-cleaner/

This appears to be much safer than using the git filter-branch command, which results in different commit hashes for everything.  I'm not actually sure how the BFG technique works under the hood, but I THINK it claims to not change the commit hashes.

If there is no way to do this other than changing all the hashes, I'm afraid we should just leave it in history and eventually suggest people clone only a fixed amount of history when they do checkouts.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#190
