### ISSUE TITLE
[ASDisplayNode] displaysAsynchronously is not recursive like neverShowPlaceholders. Simplify to single API?

### ISSUE THREAD

**Issue by skensell** [facebookarchive/AsyncDisplayKit#3045]
My original issue:
I am trying to fade in an `ASViewController` as the new `rootViewController`, but it doesn't fully render until the transition has ended, making the animated transition pointless.

My viewController is pretty simple and the main async benefits of ASDK aren't so important here, so I figured I'd just set `self.node.displaysAsynchronously = NO` to force rendering on the main thread before the transition starts.  Didn't work.

The root node has an `ASPagerNode` with 3 `ASCellNode`s each being a thin wrappers for one `ASImageNode` (it's a welcome tutorial with 3 large images).  I was eventually able to force the rendering by setting `imageNode.displaysAsynchronously = NO` on each of the `ASImageNode`s.

Why doesn't setting `displaysAsynchronously = NO` work in a recursive fashion, forcing subnodes to render synchronously?  It would be nice to effectively "turn off ASDK" for certain views where the async rendering isn't crucial.

**Comment by skensell** [comment]
Alternatively, I'd love to hear other solutions which would avoid touching `displaysAsynchronously` and could force a full rendering.  (Note, I also had to call` [self.node.pagerNode reloadDataImmediately];` in `viewDidLoad`).

**Comment by appleguy** [comment]
@skensell it is not currently designed to affect subnodes.  If this isn't clear from the documentation, we should definitely improve the comment / docs around it.

I do think it would be valuable to have a recursive version.  If you are interested in implementing this, it would be very easy to add a new bit to ASHierarchyState that controls this.  Internally one would call enterHierarchyState: and it would automatically get propagated to children.  You could have each level (in setHierarchyState:) perform self.displaysAsynchronously = YES / NO;

If you have an ASPagerNode or collection or table, you probably are looking for ASCellNode .neverShowPlaceholders.  This API works extremely well and is faster than displaysAsynchronously because it is truly concurrent: http://asyncdisplaykit.org/docs/synchronous-concurrency.html . I apologize the name isn't better :)

Please let us know if this addresses your issue (at an app level, if you can use neverShowPlaceholders) -- also message me on Slack if you're running into issues.

If your app issue is resolved, we can treat the task as a feature request for recursive displaysAsynchronously = NO (or, put more simply, a generalized API to supercede neverShowPlaceholders that works on all ASDisplayNodes rather than just ASCellNodes).  I think it could be achieved in a way that does support synchronous concurrency, which is a more tricky technique to implemented that had not been done before at the time the simple displaysAsynchronously switch was added (it's been around since the earliest pre-launch version of ASDK, whereas sync concurrency is just a year old).

**Comment by skensell** [comment]
@appleguy Thanks, it looks like `neverShowPlaceholders` is what I was looking for.  Interestingly, setting it on the `ASViewController` node didn't have any effect, but setting it on the individual `ASCellNode`s did work for me.

Another related issue, in upgrading to 2.1 my rootViewController transitions required tweaking:
```Obj-C
    [viewController.view layoutIfNeeded]; // was not necessary with ASDK 1.9
    [UIView transitionWithView:window
                      duration:0.4f
                       options:UIViewAnimationOptionTransitionCrossDissolve | UIViewAnimationOptionCurveEaseOut
                    animations:^{
                        window.rootViewController = viewController;
                    }
                    completion:nil];
```
Without the `-layoutIfNeeded` call, some strange intermediate form of the view was displayed which was not layed out properly. I dunno if I should create a separate issue for this.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#192
