### ISSUE TITLE
_ASCollectionViewCell inherits content node properties like backgroundColor? 

### ISSUE THREAD

**Issue by skensell** [facebookarchive/AsyncDisplayKit#3053]
Hey Guys, I'm in the process of upgrading from 1.9 to 2.1, and this is the first in hopefully not a long sequence of bugs which I'll report:

My issue is that I have an `ASCellNode` which sets `backgroundColor` and `cornerRadius` like so:

```Obj-C
self.backgroundColor = [[UIColor blackColor] colorWithAlphaComponent:0.25]; // in init
self.cornerRadius = self.bounds.size.height / 2.0f; // in layoutDidFinish
```
and then it seems the `backgroundColor` is transferred to the backing cell in `[_ASCollectionViewCell setNode:]` while the `cornerRadius` is not. I don't understand why _any_ property is being transferred to the backing cell and rather you just let the content node make display decisions.

It results in a funny picture like this:
<img width="85" alt="screen shot 2017-02-20 at 9 55 33 pm" src="https://cloud.githubusercontent.com/assets/3983827/23141575/b5d52c38-f7b7-11e6-84dc-23aba6298e8a.png">

You can see that there are a few problems:

1. The `backgroundColor` of the cell and the node blend to form a darker shade than initially desired.
2. The cell does not inherit the `cornerRadius` property from the node, and appears as a square.

To solve this, I was considering

Workaround 1: Add a `contentNode` subnode to each of my `ASCellNode`s and only modify _its_ `cornerRadius` and `backgroundColor`.
Workaround 2: Hack the `_ASCollectionViewCell` to have `[UIColor clearColor]`.

I went with Workaround 2, which I'm not very proud of:

```Obj-C
- (void)collectionNode:(ASCollectionNode *)collectionNode willDisplayItemWithNode:(ASCellNode *)node {
    UICollectionViewCell* cell = nil;
    UIView* view = node.isNodeLoaded ? node.view : nil;
    while (view && ![view isKindOfClass:[UICollectionViewCell class]]) {
        view = view.superview;
    }
    if (view) {
        cell = (UICollectionViewCell*)view;
    }
    cell.backgroundColor = [UIColor clearColor];
}
```

IMO, it would make more sense if `_ASCollectionViewCell` just had `[UIColor clearColor]` as its background and it shouldn't inherit any properties from the contentNode.  After looking around, I noticed `_ASTableViewCell` has the same issue.  Is this intentional? What's the reasoning?

**Comment by maicki** [comment]
@skensell Thanks for reporting! For reference just linking the PR for now: https://github.com/facebook/AsyncDisplayKit/pull/2847/files

**Comment by appleguy** [comment]
@skensell great report.  Question: why is your cell node a different size from the cell containing it?  I don't recall why this change was made, but I know it was because of a situation that required being able to set the containing cell color.

It is possible that this only makes sense to do for opaque colors, to prevent blending or bleed-through of unintended content beneath.  But I agree with you, ideally the ASCellNode is the same size as the parent and it wouldn't matter.

Lastly, it's really expensive to use cornerRadius on a cell, so consider if you can use an ASButtonNode or ASImageNode with [UIImage as_resizableRoundedImageWithCornerRadius:].  It works with semitransparent background colors and also content showing through behind the corners, as long as the background color is flat (single color, even if alpha) and there aren't any views moving through the inside of the corners that need to be clipped.  http://asyncdisplaykit.org/docs/corner-rounding.html . Hope this is helpful, but I know it's not your main issue and we'll try to help out there too :)

**Comment by skensell** [comment]
@appleguy I think the image I included may be misleading you -- the size of the cell and the node are the same. The outermost gray in the image is the background of the `ASCollectionNode`. Of concern here is the inner 90 degree corner on `_ASCollectionViewCell` and the rounded corner of its node within (which has the same frame).

Thanks for the advice on the corner radius. I do usually try other methods, but sometimes I _cut corners_ and just use `cornerRadius` when performance isn't a huge concern.

**Comment by garrettmoon** [comment]
I think this has been addressed, please re-open on Texture if not. https://github.com/texturegroup/texture/issues
