### ISSUE TITLE
[ReactiveCocoa] Discussing techniques for interoperation between RAC and ASDK.

### ISSUE THREAD

**Issue by bimawa** [facebookarchive/AsyncDisplayKit#886]
I have calculation layouts in Spec`s in one thred, and call with new data and recolculation from another thred. And it make deadlock in mutex. How i can get info about complited colculation all Layouts in self Node?

Now i solve my taks with overading 

``` obj-c
- (void)layoutDidFinish
{
    [super layoutDidFinish];
    self.isFinalLayoutable = YES;
}
```

method and set a flag isFinalLayoutable to YES. It`s a good solution or no?
After that i load new data to ASTextNode and recolculate Node again, now its working.

**Comment by appleguy** [comment]
@bimawa the .isFinalLayoutable flag is not intended for users of the framework to set in this situation.  It is actually a very advanced feature that few users should need (@rcancro, we should make sure this is properly documented).

You can check the .calculatedLayout property to get the currently calculated ASLayout, which will not be set until the layout pass is completely done.  However, I caution that what you describe with multiple threads being involved sounds risky / difficult to get right.  I would be happy to advise further if you are able to explain in more detail 1) what you are trying to accomplish, and 2) what the details of your multithreading technique are.

**Comment by bimawa** [comment]
Hi @appleguy, it's again `ReactiveCocoa`, i can't without use it.
I just have loaded Data for my Node from background Threads and if it will do fast, and ADK layoutSpec finish not, I'm catch mutex deadlock. Go to try show in a picture:
![untitled](https://cloud.githubusercontent.com/assets/1393809/11450489/342bffa6-95c3-11e5-92f6-45eddd930afb.png)

I do not know why but something does not work for observe `calculatedLayout` property in RacObserve. However  `self.isFinalLayoutable` Observed perfect in next code:

```obj-c

[[RACSignal combineLatest:@[RACObserve(model, shopTitleName), RACObserve(self, isFinalLayoutable)] reduce:^NSString *(NSString *shopTitle, NSNumber *isFinalLayout) {
           if (!isFinalLayout.boolValue)
               return nil;
           return shopTitle;
       }] subscribeNext:^(NSString *shopTitle) {
           if (shopTitle)
           {
               self.shopNameTitle.attributedString = [[NSAttributedString alloc] initWithString:shopTitle attributes:[self p_titleAttributes]];
           }
       }];
```

**Comment by appleguy** [comment]
@bimawa Cool diagram, thanks!  You are one of the only people I know who has attempted to use ReactiveCocoa with ASDK - the only other one I currently know of is @RuiAAPeres.

I think this is very likely to be perilous.  RAC is an amazing, very interesting framework — but these two are not known to be compatible, and from everything I know about RAC, they are pretty fundamentally difficult to integrate.

isFinalLayoutable is not to be used in the way that you're using it.  So be aware that it may seriously break other functionality.  This affects the internals of the layout system in ways that you are not intending, so it isn't a stable solution for what you'd like to do.  I'm not sure how RAC observation works, but if it is at all related to KVO, note that the ASDK properties (intentionally) are not KVO / KVC-compliant.

That said, from the diagram above, a few comments:

- ASLayoutSpec is not mutable after you have returned it from -layoutSpecThatFits:.  So, after the new data arrives, you must not modify any existing layout.  I in fact don't see a need for you to check if the current layout is done.
- Instead, I would expect you need to call something like -invalidateLayout and -setNeedsLayout, possibly -layoutIfNeeded if you want it to occur immediately (although the latter method must be called on the main thread, I'm pretty sure the others are thread safe - look at the implementation to confirm, as it is uncommon to use them off the main thread, but apparently with RAC this may be a useful property).
- It may be better to use a technique such as allocating a new node hierarchy once the new data has returned, and once it has finished layout (you can call -measureWithSizeRange: on any background thread yourself - and it will execute in-line, so you will no when it is done), you can "wholesale replace" the entire previous node hierarchy. This would make it so that it doesn't matter if the previous node hierarchy is finished or completed with layout.  You could use something like reloadRow/ItemAtIndexPath: and return the new ASCellNode, or manually replace a subnode of an existing ASCellNode.

I'm sure there are techniques that can be used to make this work, and I am open to changes to ASDK that will improve the compatibility with RAC if they are proposed by the community and don't negatively affect the complexity or behavior of ASDK apps that do not use RAC.  I'll rename this task for further discussion about RAC.

**Comment by bimawa** [comment]
@appleguy yea its not so hard how as it may seem. Just need reserch how working with threads and we can realte this two awesome frameworks together, i think.
I try all ur advice, thx for it!, And yea its realy helped. Now i stay on solution with this code:

```obj-c
dispatch_async(dispatch_get_main_queue(), ^{
            [self invalidateCalculatedLayout];
            [self setNeedsLayout];
}); 
```
After deadline i research this moment better, I am interested to `- (void)layoutDidFinish` method. its too realy helped. If u recomend not use `isFinalLayoutable` i can use myself var, right?
Thx for `future` branch! ;)

**Comment by RuiAAPeres** [comment]
From my experience with RAC and AsyncDisplayKit, I keep RAC's logic entirely on the ViewModel side, and the View is completely oblivious about this. Given this:

1. RAC tends to add a bit of overhead (performance hit). This might be acceptable, but if you are using AsyncDisplayKit, that performance hit, might be too much for you.
2. Threading is really hard, and it seems, there are a lot of places where your solution can go wrong. As @appleguy said, you shouldn't rely on `isFinalLayoutable`. 

@appleguy 
> I'm not sure how RAC observation works, but if it is at all related to KVO, note that the ASDK properties (intentionally) are not KVO / KVC-compliant.

It's related to KVO. 

@bimawa 
Another thing (related to RAC specifically) :

```
[[RACSignal combineLatest:@[RACObserve(model, shopTitleName), RACObserve(self, isFinalLayoutable)] reduce:^NSString *(NSString *shopTitle, NSNumber *isFinalLayout) {
           if (!isFinalLayout.boolValue)
               return nil;
           return shopTitle;
       }] subscribeNext:^(NSString *shopTitle) {
           if (shopTitle)
           {
               self.shopNameTitle.attributedString = [[NSAttributedString alloc] initWithString:shopTitle attributes:[self p_titleAttributes]];
           }
       }];
```

You should avoid injecting side effects with `subscribeNext`. It's a better practise to go like this:

```
RAC(self.shopNameTitle, attributedString) = [[RACSignal combineLatest:@[RACObserve(model, shopTitleName), RACObserve(self, isFinalLayoutable)] reduce:^NSString *(NSString *shopTitle, NSNumber *isFinalLayout) {
           if (!isFinalLayout.boolValue)
               return nil;
           return shopTitle;
       }]
```

The code above is not exactly like the one you have, but in a nutshell, it's preferable to bind the result to the variable via the `RAC()` macro. You should also favor `filter` instead of using stuff like `if (!isFinalLayout.boolValue)`.

**Comment by bimawa** [comment]
>Another thing (related to RAC specifically) :
@RuiAAPeres Yea i know that. i just research behavior of the different variants.
Thx a lot for u reply, mb later we will be RAC features made simplest way...

**Comment by bimawa** [comment]
@appleguy i start develop wrapping for RAC https://github.com/bimawa/AsyncDisplayKit/tree/ReactiveCocoa-2.5 help me pls made it correctly

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#112
