### ISSUE TITLE
[ASTableView] Test project demonstrating undesired animations on empty update transaction.

### ISSUE THREAD

**Issue by tomizimobile** [facebookarchive/AsyncDisplayKit#922]
Using this sample project here: https://github.com/tomizimobile/ASDKSearchIssue, which is using AsyncDisplayKit v1.9.3

Currently, the project is working mostly as expected. I've come across a UI issue when updating the tableView using `beginUpdates()`/`endUpdates()` - even though I've set all of my delete/insert animation options to `.None`, and even after wrapping my `beginUpdates()`/`endUpdates()` in `UIView.setAnimationsEnabled(false)`/`UIView.setAnimationsEnabled(true)` or `UIView.performWithoutAnimation`, animations still occur.

In order to get around the animation issue, I tried always calling `reloadData()` or `reloadDataImmediately()` instead of calculating which rows/sections should be inserted/deleted. However, when I do this, i get a crash in the delegate method `-[tableView:titleForHeaderInSection:]`, because it's calling it with a section that is out of range of the newly-filtered data. This can be easily reproduced in the sample project by changing line 106 in "ViewController.swift" to: `if tableView.numberOfSections == 0 || true`.

**Comment by Adlai-Holler** [comment]
@tomizimobile Thanks for another awesomely-thorough report!

On animations: I believe the reason `setAnimationsEnabled` isn't in this case is, ASTableView enqueues those animations asynchronously after returning from `endUpdates`. In your test project, calling `tableView.endUpdatesAnimated(false, completion: nil)` does the trick for me. It's not API-compatible with UIKit, but is that OK?

On crashing when reloading data: This is indeed a bug in the framework! Diving in, I've found that during the `[super reloadData]`, `ASTableView` is returning 12 sections (the pre-filter value) when your table view data source is only returning 6 – the data controller must requery the underlying data source immediately, or else this `titleForHeader:` crash is inevitable. I tried shuffling around the implementation of `ASTableView.reloadData` but no luck.

The fact that `titleForHeader:` is a delegate method, not a data-source method, is kind of screwing with the data architecture of ASTableView, because it allows the client to talk directly to UITableView about its data, which isn't what's up. @nguyenhuy can you think of an approach that wouldn't tear ASTableView apart?

**Comment by tomizimobile** [comment]
@Adlai-Holler Hah, somehow I totally missed that `endUpdatesAnimated` even existed... it's perfect. That solves my animation issue, and the way I was doing it previously clearly can't realistically be supported. But if nothing else, it helped me root out a crash. 

Since I don't really have a need to `reloadData` anymore (nor did I really want to, given the performance hit), the crash isn't something I'm immediately worried about, but if anyone puts a fix in place and needs help testing it out, I'll be glad to help.

**Comment by nguyenhuy** [comment]
@tomizimobile `endUpdatesAnimated` is indeed the way to go in this case. Thanks for the helpful test repo. I can reproduce the crash with `reloadData` and agree with @Adlai-Holler that it is a framework bug. I also agree that clients shouldn't be allowed to talk directly to UITableView and report header titles. Instead, ASTableView should intercept `titleForHeader` calls and do something clever. I'm thinking about asking ASTableView to cache all old titles, and then return them while UITableView is reloading ([here](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTableView.mm#L330)). Cache will be cleared later on, either right after UITableView's reload is done or after the underlying data controller finished. 

Another approach is to ban `titleForHeader` completely and encourage those who need to show header titles to switch to ASCollectionView instead. There is a stable implementation of supplementary views support. And it will be an easy switch because all the nodes are already of type ASCellNode.

What do you guys think?

**Comment by appleguy** [comment]
Still thinking about this, going to try to look into it soon.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#114
